name: Build Docker and Optional Push - Researcher

on:
  push:
    branches: [byoc-researcher]
  pull_request:
    branches: [byoc-researcher]
    types:
      - opened
      - ready_for_review
      - reopened
      - synchronize
  merge_group:
  workflow_dispatch:

jobs:
  docker-build:
    strategy:
      matrix:
        include:
          - app_name: byoaia-app
            dockerfile: src/WebApp.Dockerfile
            password_secret: DOCKER_PASSWORD_RESEARCHASSISTANT

    uses: ./.github/workflows/build-docker.yml
    with:
      registry: byoaiacontainerreg.azurecr.io
      username: byoaiacontainerreg
      password_secret: ${{ matrix.password_secret }}
      app_name: ${{ matrix.app_name }}
      dockerfile: ${{ matrix.dockerfile }}
      push: ${{ github.ref_name == 'byoc-researcher' || github.ref_name == 'dependabotchanges' }} 
    secrets: inherit
