name: Test Workflow with Coverage - Researcher

on:
  push:
    branches: [byoc-researcher]
  pull_request:
    branches: [byoc-researcher]
    types:
      - opened
      - ready_for_review
      - reopened
      - synchronize

jobs:
  test_research_assistant:
    name: Research Assistant Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Backend Dependencies
        run: |
          cd src
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install coverage pytest pytest-cov pytest-asyncio

      - name: Run Backend Tests with Coverage
        run: |
          cd src
          python -m pytest -vv --cov=. --cov-report=xml --cov-report=html --cov-report=term-missing --cov-fail-under=80 --junitxml=coverage-junit.xml
      - uses: actions/upload-artifact@v4
        with:
          name: research-assistant-coverage
          path: |
            src/coverage.xml
            src/coverage-junit.xml
            src/htmlcov/
